version: '3.8'

services:
  # Redis for caching and session management
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - climate-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend API (FastAPI) - Uses Supabase PostgreSQL
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=redis://redis:6379/0
      - GOOGLE_EARTH_ENGINE_SERVICE_ACCOUNT=${GOOGLE_EARTH_ENGINE_SERVICE_ACCOUNT}
      - AFRICAS_TALKING_API_KEY=${AFRICAS_TALKING_API_KEY}
      - AFRICAS_TALKING_USERNAME=${AFRICAS_TALKING_USERNAME}
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - SECRET_KEY=${SECRET_KEY:-dev_secret_key}
      - ENVIRONMENT=${ENVIRONMENT:-development}
    depends_on:
      - redis
    networks:
      - climate-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend PWA (Next.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - climate-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Background worker for async tasks
  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python -m app.worker
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=redis://redis:6379/0
      - GOOGLE_EARTH_ENGINE_SERVICE_ACCOUNT=${GOOGLE_EARTH_ENGINE_SERVICE_ACCOUNT}
      - AFRICAS_TALKING_API_KEY=${AFRICAS_TALKING_API_KEY}
      - AFRICAS_TALKING_USERNAME=${AFRICAS_TALKING_USERNAME}
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    depends_on:
      - redis
    networks:
      - climate-network
    restart: unless-stopped

volumes:
  redis_data:

networks:
  climate-network:
    driver: bridge
